public enum ItemEffectType
{
    EquipWeapon,
    WeaponRangeUp,
    WeaponCooldownUp,
    WeaponMajorUpgrade,
    AttackUp,
    ElementalAttackUp,
    ArmorPenetrationUp,
    MaxHealthUp,
    MoveSpeedUp,
    MoveSpeedPercentUp,
    CritRateUp,
    CritEffectUp,
    DefenseUp,
    CooldownReductionUp,
    ExpBonusUp,
    GoldBonusUp,
    AttackDamageBonusUp,
    ElementalDamageBonusUp
}
